/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inventory.UI;

import com.inventory.DAO.CustomerDAO;
import com.inventory.DAO.ProductDAO;
import com.inventory.DAO.SupplierDAO;
import com.inventory.DAO.UserDAO;
import com.inventory.DTO.ProductDTO;
import com.inventory.DTO.SupplierDTO;
import com.inventory.Salles.CaisseLoan;
import com.inventory.Salles.SallePage;
import com.inventory.raport.PDFTable;
import com.inventory.tables.ClientTable;
import com.inventory.tables.FournisseurTable;
import com.inventory.tables.ProductTable;
import com.inventory.tables.PurcahseTable;
import com.inventory.tables.SalleTable;
import com.inventory.tables.UserTable;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author deidine
 */
public class Dashboard extends javax.swing.JFrame {

    private static int counterPagination = 0;
    int limitPagination = 20;
    PurcahseTable prchtb = new PurcahseTable();
    ClientTable cltb = new ClientTable();
    SalleTable sltbl = new SalleTable();
    UserTable usertbl = new UserTable();

    ProductTable prtbl = new ProductTable();
    FournisseurTable frtbl = new FournisseurTable();

    /**
     * Creates new form Dashboard2
     */
    static String username="deodone";

    public Dashboard(String username) {
        this.username = username;
        System.out.println("eheh"+this.username);
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon("resources/logo.png").getImage());

        // setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        try {
            loadData();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        setExtendedState(JFrame.MAXIMIZED_BOTH); // this for full screen
        // setUndecorated(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelFournisseur = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        serchFournisseur = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        prevFournisseur = new javax.swing.JButton();
        nextFournisseur = new javax.swing.JButton();
        deleteFournisseur = new javax.swing.JButton();
        editFournisseur = new javax.swing.JButton();
        addFournisseur = new javax.swing.JButton();
        imprimer = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollTabelTransaksi11 = new javax.swing.JScrollPane();
        tablFourniseur = new javax.swing.JTable();
        panelClient = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        serchClient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nextClient = new javax.swing.JButton();
        prevClient = new javax.swing.JButton();
        deleteClient = new javax.swing.JButton();
        editClient = new javax.swing.JButton();
        addClient = new javax.swing.JButton();
        imprimer4 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollTabelTransaksi6 = new javax.swing.JScrollPane();
        tabelClient = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        serchPurchase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nextPurchase = new javax.swing.JButton();
        prevPurchase = new javax.swing.JButton();
        deletePurchase = new javax.swing.JButton();
        addPurchase = new javax.swing.JButton();
        imprimer3 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollTabelTransaksi7 = new javax.swing.JScrollPane();
        tabelIPurchase = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        serchProduct = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nextProduct = new javax.swing.JButton();
        prevProduct = new javax.swing.JButton();
        deleteProduit = new javax.swing.JButton();
        editProduit = new javax.swing.JButton();
        addProduit = new javax.swing.JButton();
        imprimer2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollTabelTransaksi9 = new javax.swing.JScrollPane();
        tabelProduit = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollTabelTransaksi10 = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();
        addUser = new javax.swing.JButton();
        editUser = new javax.swing.JButton();
        deleteUser = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        serchUser = new javax.swing.JTextField();
        jMenuBarInfoPengembang = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuRefresh = new javax.swing.JMenuItem();
        jMenuIExit1 = new javax.swing.JMenuItem();
        jMenuIExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        infoAplikasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serchFournisseur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serchFournisseurKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setText("Chercher");

        prevFournisseur.setBackground(new java.awt.Color(255, 51, 51));
        prevFournisseur.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        prevFournisseur.setForeground(new java.awt.Color(51, 51, 0));
        prevFournisseur.setText("Prev");
        prevFournisseur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        prevFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevFournisseurActionPerformed(evt);
            }
        });

        nextFournisseur.setBackground(new java.awt.Color(255, 51, 51));
        nextFournisseur.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        nextFournisseur.setForeground(new java.awt.Color(51, 51, 0));
        nextFournisseur.setText("Next");
        nextFournisseur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        nextFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFournisseurActionPerformed(evt);
            }
        });

        deleteFournisseur.setBackground(new java.awt.Color(255, 51, 51));
        deleteFournisseur.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        deleteFournisseur.setForeground(new java.awt.Color(51, 51, 0));
        deleteFournisseur.setText("suprimer");
        deleteFournisseur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        deleteFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFournisseurActionPerformed(evt);
            }
        });

        editFournisseur.setBackground(new java.awt.Color(255, 255, 0));
        editFournisseur.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        editFournisseur.setForeground(new java.awt.Color(51, 51, 0));
        editFournisseur.setText("editer");
        editFournisseur.setBorderPainted(false);
        editFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFournisseurActionPerformed(evt);
            }
        });
        editFournisseur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editFournisseurKeyPressed(evt);
            }
        });

        addFournisseur.setBackground(new java.awt.Color(51, 255, 51));
        addFournisseur.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        addFournisseur.setForeground(new java.awt.Color(51, 0, 51));
        addFournisseur.setText("Ajouter");
        addFournisseur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFournisseurActionPerformed(evt);
            }
        });

        imprimer.setBackground(new java.awt.Color(51, 255, 51));
        imprimer.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        imprimer.setForeground(new java.awt.Color(51, 0, 51));
        imprimer.setText("Imprimer");
        imprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(nextFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prevFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serchFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteFournisseur)
                            .addComponent(serchFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prevFournisseur)
                            .addComponent(nextFournisseur))
                        .addComponent(editFournisseur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addFournisseur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tablFourniseur.setOpaque(true);
        tablFourniseur.setRowHeight(30);
        tablFourniseur.getTableHeader().setReorderingAllowed(false);
        jScrollTabelTransaksi11.setViewportView(tablFourniseur);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi11)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollTabelTransaksi11, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFournisseurLayout = new javax.swing.GroupLayout(panelFournisseur);
        panelFournisseur.setLayout(panelFournisseurLayout);
        panelFournisseurLayout.setHorizontalGroup(
            panelFournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFournisseurLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFournisseurLayout.setVerticalGroup(
            panelFournisseurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFournisseurLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fournisseur", panelFournisseur);

        serchClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serchClientKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Chercher");

        nextClient.setBackground(new java.awt.Color(255, 51, 51));
        nextClient.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        nextClient.setForeground(new java.awt.Color(51, 51, 0));
        nextClient.setText("Next");
        nextClient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        nextClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextClientActionPerformed(evt);
            }
        });

        prevClient.setBackground(new java.awt.Color(255, 51, 51));
        prevClient.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        prevClient.setForeground(new java.awt.Color(51, 51, 0));
        prevClient.setText("Prev");
        prevClient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        prevClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevClientActionPerformed(evt);
            }
        });

        deleteClient.setBackground(new java.awt.Color(255, 51, 51));
        deleteClient.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        deleteClient.setForeground(new java.awt.Color(51, 51, 0));
        deleteClient.setText("suprimer");
        deleteClient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        deleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClientActionPerformed(evt);
            }
        });

        editClient.setBackground(new java.awt.Color(255, 255, 0));
        editClient.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        editClient.setForeground(new java.awt.Color(51, 51, 0));
        editClient.setText("editer");
        editClient.setBorderPainted(false);
        editClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClientActionPerformed(evt);
            }
        });
        editClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editClientKeyPressed(evt);
            }
        });

        addClient.setBackground(new java.awt.Color(51, 255, 51));
        addClient.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        addClient.setForeground(new java.awt.Color(51, 0, 51));
        addClient.setText("Ajouter");
        addClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientActionPerformed(evt);
            }
        });

        imprimer4.setBackground(new java.awt.Color(51, 255, 51));
        imprimer4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        imprimer4.setForeground(new java.awt.Color(51, 0, 51));
        imprimer4.setText("Imprimer");
        imprimer4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimer4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(addClient)
                .addGap(18, 18, 18)
                .addComponent(editClient, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(imprimer4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(prevClient, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextClient, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(nextClient)
                        .addComponent(prevClient)
                        .addComponent(imprimer4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        tabelClient.setIntercellSpacing(new java.awt.Dimension(10, 5));
        tabelClient.setOpaque(true);
        tabelClient.setRowHeight(30);
        tabelClient.getTableHeader().setReorderingAllowed(false);
        jScrollTabelTransaksi6.setViewportView(tabelClient);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi6)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollTabelTransaksi6, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelClientLayout = new javax.swing.GroupLayout(panelClient);
        panelClient.setLayout(panelClientLayout);
        panelClientLayout.setHorizontalGroup(
            panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelClientLayout.setVerticalGroup(
            panelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LES CLIENT", panelClient);

        serchPurchase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serchPurchaseKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("Chercher");

        nextPurchase.setBackground(new java.awt.Color(255, 51, 51));
        nextPurchase.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        nextPurchase.setForeground(new java.awt.Color(51, 51, 0));
        nextPurchase.setText("Next");
        nextPurchase.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        nextPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPurchaseActionPerformed(evt);
            }
        });

        prevPurchase.setBackground(new java.awt.Color(255, 51, 51));
        prevPurchase.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        prevPurchase.setForeground(new java.awt.Color(51, 51, 0));
        prevPurchase.setText("Prev");
        prevPurchase.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        prevPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevPurchaseActionPerformed(evt);
            }
        });

        deletePurchase.setBackground(new java.awt.Color(255, 51, 51));
        deletePurchase.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        deletePurchase.setForeground(new java.awt.Color(51, 51, 0));
        deletePurchase.setText("suprimer");
        deletePurchase.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        deletePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePurchaseActionPerformed(evt);
            }
        });

        addPurchase.setBackground(new java.awt.Color(51, 255, 51));
        addPurchase.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        addPurchase.setForeground(new java.awt.Color(51, 0, 51));
        addPurchase.setText("Ajouter");
        addPurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPurchaseActionPerformed(evt);
            }
        });

        imprimer3.setBackground(new java.awt.Color(51, 255, 51));
        imprimer3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        imprimer3.setForeground(new java.awt.Color(51, 0, 51));
        imprimer3.setText("Imprimer");
        imprimer3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimer3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(addPurchase)
                .addGap(126, 126, 126)
                .addComponent(deletePurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(imprimer3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(prevPurchase)
                .addGap(66, 66, 66)
                .addComponent(nextPurchase)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(serchPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deletePurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serchPurchase)
                        .addComponent(jLabel2)
                        .addComponent(imprimer3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addPurchase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prevPurchase)
                        .addComponent(nextPurchase)))
                .addGap(0, 0, 0))
        );

        tabelIPurchase.setOpaque(true);
        tabelIPurchase.setRowHeight(30);
        tabelIPurchase.getTableHeader().setReorderingAllowed(false);
        jScrollTabelTransaksi7.setViewportView(tabelIPurchase);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi7)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi7, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Les Commende", jPanel2);

        serchProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serchProductKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setText("Chercher");

        nextProduct.setBackground(new java.awt.Color(255, 51, 51));
        nextProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        nextProduct.setForeground(new java.awt.Color(51, 51, 0));
        nextProduct.setText("Next");
        nextProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        nextProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextProductActionPerformed(evt);
            }
        });

        prevProduct.setBackground(new java.awt.Color(255, 51, 51));
        prevProduct.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        prevProduct.setForeground(new java.awt.Color(51, 51, 0));
        prevProduct.setText("Prev");
        prevProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        prevProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevProductActionPerformed(evt);
            }
        });

        deleteProduit.setBackground(new java.awt.Color(255, 51, 51));
        deleteProduit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        deleteProduit.setForeground(new java.awt.Color(51, 51, 0));
        deleteProduit.setText("suprimer");
        deleteProduit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        deleteProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProduitActionPerformed(evt);
            }
        });

        editProduit.setBackground(new java.awt.Color(255, 255, 0));
        editProduit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        editProduit.setForeground(new java.awt.Color(51, 51, 0));
        editProduit.setText("editer");
        editProduit.setBorderPainted(false);
        editProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProduitActionPerformed(evt);
            }
        });
        editProduit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editProduitKeyPressed(evt);
            }
        });

        addProduit.setBackground(new java.awt.Color(51, 255, 51));
        addProduit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        addProduit.setForeground(new java.awt.Color(51, 0, 51));
        addProduit.setText("Ajouter");
        addProduit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProduitActionPerformed(evt);
            }
        });

        imprimer2.setBackground(new java.awt.Color(51, 255, 51));
        imprimer2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        imprimer2.setForeground(new java.awt.Color(51, 0, 51));
        imprimer2.setText("Imprimer");
        imprimer2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imprimer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimer2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(addProduit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(deleteProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(imprimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prevProduct)
                .addGap(61, 61, 61)
                .addComponent(nextProduct)
                .addGap(58, 58, 58)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addComponent(serchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(serchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addProduit)
                            .addComponent(editProduit)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prevProduct)
                        .addComponent(nextProduct)
                        .addComponent(imprimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        tabelProduit.setIntercellSpacing(new java.awt.Dimension(10, 5));
        tabelProduit.setOpaque(true);
        tabelProduit.setRowHeight(30);
        tabelProduit.getTableHeader().setReorderingAllowed(false);
        jScrollTabelTransaksi9.setViewportView(tabelProduit);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollTabelTransaksi9))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollTabelTransaksi9, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Les Produits", jPanel3);

        tabelUser.setIntercellSpacing(new java.awt.Dimension(10, 5));
        tabelUser.setOpaque(true);
        tabelUser.setRowHeight(30);
        tabelUser.getTableHeader().setReorderingAllowed(false);
        jScrollTabelTransaksi10.setViewportView(tabelUser);

        addUser.setBackground(new java.awt.Color(51, 255, 51));
        addUser.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        addUser.setForeground(new java.awt.Color(51, 0, 51));
        addUser.setText("Ajouter");
        addUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        editUser.setBackground(new java.awt.Color(255, 255, 0));
        editUser.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        editUser.setForeground(new java.awt.Color(51, 51, 0));
        editUser.setText("editer");
        editUser.setBorderPainted(false);
        editUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserActionPerformed(evt);
            }
        });
        editUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editUserKeyPressed(evt);
            }
        });

        deleteUser.setBackground(new java.awt.Color(255, 51, 51));
        deleteUser.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        deleteUser.setForeground(new java.awt.Color(51, 51, 0));
        deleteUser.setText("suprimer");
        deleteUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), new java.awt.Color(102, 102, 0), new java.awt.Color(153, 153, 0)));
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setText("Chercher");

        serchUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serchUserKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollTabelTransaksi10, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editUser, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addComponent(serchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollTabelTransaksi10, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1039, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("vendeur/user", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Option");

        jMenuRefresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuRefresh.setText("Afficher Le nouveaux cahngement");
        jMenuRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRefreshActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuRefresh);

        jMenuIExit1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuIExit1.setText("Page De Vente");
        jMenuIExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIExit1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIExit1);

        jMenuIExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuIExit.setText("Exit");
        jMenuIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIExit);

        jMenuBarInfoPengembang.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Info Pengembang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        infoAplikasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        infoAplikasi.setText("Info Aplikasi");
        infoAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoAplikasiActionPerformed(evt);
            }
        });
        jMenu2.add(infoAplikasi);

        jMenuBarInfoPengembang.add(jMenu2);

        setJMenuBar(jMenuBarInfoPengembang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serchFournisseurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchFournisseurKeyReleased
        String text = serchFournisseur.getText();
        loadSearchDataFournisseur(text);  // TODO add your handling code here:
    }//GEN-LAST:event_serchFournisseurKeyReleased

    private void prevFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevFournisseurActionPerformed
        --counterPagination;
        // Set Tabel Model for Barang
        if (counterPagination * limitPagination <= 0) {
            prevFournisseur.setEnabled(false);
            nextFournisseur.setEnabled(true);
        } else {
            prevFournisseur.setEnabled(true);
            nextFournisseur.setEnabled(true);
        }
        tablFourniseur.setModel(frtbl.generateTable(limitPagination, counterPagination));
        // TODO add your handling code here:
    }//GEN-LAST:event_prevFournisseurActionPerformed

    private void nextFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFournisseurActionPerformed
        ++counterPagination;

        if (counterPagination >= cltb.countRecords() / limitPagination) {
            nextFournisseur.setEnabled(false);
            prevFournisseur.setEnabled(true);
        } else {
            nextFournisseur.setEnabled(true);
            prevFournisseur.setEnabled(true);
        }
        tablFourniseur.setModel(frtbl.generateTable(limitPagination, counterPagination));
        // TODO add your handling code here:
    }//GEN-LAST:event_nextFournisseurActionPerformed

    private void deleteFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFournisseurActionPerformed
        if (tablFourniseur.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "SLV slectionner un line dans le table pour le suprimer.");
        } else {
            int opt = JOptionPane.showConfirmDialog(
                    this,
                    "tu es sure de suprimer le fournisseur?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION) {
                new SupplierDAO()
                        .deleteSupplierDAO(tablFourniseur.getValueAt(tablFourniseur.getSelectedRow(), 0).toString());
                refrech();
                try {
                    loadData();
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        }     // TODO add your handling code here:
    }//GEN-LAST:event_deleteFournisseurActionPerformed

    private void editFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFournisseurActionPerformed
        if (tablFourniseur.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "SLV slectionner un line dans le table pour le suprimer.");
        } else {
            int row = tablFourniseur.getSelectedRow();
            int col = tablFourniseur.getColumnCount();
            Object[] data = new Object[col];

            for (int i = 0; i < col; i++) {

                data[i] = tablFourniseur.getValueAt(row, i);
            }
            new FournisseurForm(true, false, data);

            SupplierDTO supplierDTOEdit = new SupplierDTO();

            System.out.println(supplierDTOEdit.toString());
            refrech();
        }     // TODO add your handling code here:
    }//GEN-LAST:event_editFournisseurActionPerformed

    private void editFournisseurKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editFournisseurKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editFournisseurKeyPressed

    private void addFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFournisseurActionPerformed
        new FournisseurForm(false, true, null);
        refrech();        // TODO add your handling code here:
    }//GEN-LAST:event_addFournisseurActionPerformed

    private void serchClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchClientKeyReleased
        String text = serchClient.getText();
        loadSearchDataClient(text);
        // TODO add your handling code here:
    }//GEN-LAST:event_serchClientKeyReleased

    private void nextClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextClientActionPerformed
        ++counterPagination;

        if (counterPagination >= cltb.countRecords() / limitPagination) {
            nextClient.setEnabled(false);
            prevClient.setEnabled(true);
        } else {
            nextClient.setEnabled(true);
            prevClient.setEnabled(true);
        }
        tabelClient.setModel(cltb.generateTable(limitPagination, counterPagination));
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_nextClientActionPerformed

    private void prevClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevClientActionPerformed
        --counterPagination;
        // Set Tabel Model for Barang
        if (counterPagination * limitPagination <= 0) {
            prevClient.setEnabled(false);
            nextClient.setEnabled(true);
        } else {
            prevClient.setEnabled(true);
            nextClient.setEnabled(true);
        }
        tabelClient.setModel(cltb.generateTable(limitPagination, counterPagination));
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_prevClientActionPerformed

    private void deleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClientActionPerformed
        CustomerDAO customerDAO = new CustomerDAO();
        if (tabelClient.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "il vaut selectionner un line dans le tableux.");
        } else {
            int opt = JOptionPane.showConfirmDialog(
                    this,
                    "tu sur de suprimer?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION) {
                customerDAO.deleteCustomerDAO(tabelClient.getValueAt(tabelClient.getSelectedRow(), 0).toString());
                refrech();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteClientActionPerformed

    private void editClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClientActionPerformed
        if (tabelClient.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "il vaut selectionner un line dans le tableau .");
        } else {
            int row = tabelClient.getSelectedRow();
            int col = tabelClient.getColumnCount();
            Object[] data = new Object[col];

            for (int i = 0; i < col; i++) {

                data[i] = tabelClient.getValueAt(row, i);
            }

            new Clientform(true, false, data);
            refrech();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_editClientActionPerformed

    private void editClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editClientKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editClientKeyPressed

    private void addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientActionPerformed
        new Clientform(false, true, null);
        refrech();        // TODO add your handling code here:
    }//GEN-LAST:event_addClientActionPerformed

    private void serchPurchaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchPurchaseKeyReleased
        String text = serchPurchase.getText();
        loadSearchDataPurchase(text);
        // TODO add your handling code here:
    }//GEN-LAST:event_serchPurchaseKeyReleased

    private void nextPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPurchaseActionPerformed
        ++counterPagination;

        if (counterPagination >= prtbl.countRecords() / limitPagination) {
            nextPurchase.setEnabled(false);
            prevPurchase.setEnabled(true);
        } else {
            nextPurchase.setEnabled(true);
            prevPurchase.setEnabled(true);
        }
        tabelIPurchase.setModel(prchtb.generateTable(limitPagination, counterPagination));
        // TODO add your handling code here:
    }//GEN-LAST:event_nextPurchaseActionPerformed

    private void prevPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevPurchaseActionPerformed

        --counterPagination;
        // Set Tabel Model for Barang
        if (counterPagination * limitPagination <= 0) {
            prevPurchase.setEnabled(false);
            nextPurchase.setEnabled(true);
        } else {
            prevPurchase.setEnabled(true);
            nextPurchase.setEnabled(true);
        }
        tabelIPurchase.setModel(prchtb.generateTable(limitPagination, counterPagination));
        // TODO add your handling code here:
    }//GEN-LAST:event_prevPurchaseActionPerformed

    private void deletePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePurchaseActionPerformed
        if (tabelIPurchase.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "il vaut selection un line dans le table.");
        } else {
            int opt = JOptionPane.showConfirmDialog(
                    null,
                    "tu es sure de suprimer?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION) {
                new ProductDAO().deletePurchaseDAO((int) tabelIPurchase.getValueAt(tabelIPurchase.getSelectedRow(), 0));
                // new ProductDAO().editPurchaseStock(prodCode, quantity);
                // loadDataSet();
                refrech();
            }
        }      // TODO add your handling code here:
    }//GEN-LAST:event_deletePurchaseActionPerformed

    private void addPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPurchaseActionPerformed
        new PurchaseForm();
        refrech();        // TODO add your handling code here:
    }//GEN-LAST:event_addPurchaseActionPerformed

    private void serchProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchProductKeyReleased
        String text = serchProduct.getText();
        loadSearchDataProduct(text);
        // TODO add your handling code here:
    }//GEN-LAST:event_serchProductKeyReleased

    private void nextProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextProductActionPerformed
        ++counterPagination;

        if (counterPagination >= prtbl.countRecords() / limitPagination) {
            nextProduct.setEnabled(false);
            prevProduct.setEnabled(true);
        } else {
            nextProduct.setEnabled(true);
            prevProduct.setEnabled(true);
        }
        tabelProduit.setModel(prtbl.generateTable(limitPagination, counterPagination));

        // TODO add your handling code here:
    }//GEN-LAST:event_nextProductActionPerformed

    private void prevProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevProductActionPerformed
        --counterPagination;
        // Set Tabel Model for Barang
        if (counterPagination * limitPagination <= 0) {
            prevProduct.setEnabled(false);
            nextProduct.setEnabled(true);
        } else {
            prevProduct.setEnabled(true);
            nextProduct.setEnabled(true);
        }
        tabelProduit.setModel(prtbl.generateTable(limitPagination, counterPagination));
        // TODO add your handling code here:
    }//GEN-LAST:event_prevProductActionPerformed

    private void deleteProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProduitActionPerformed
        if (tabelProduit.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "il vaut slectionner un line dans le tableau.");
        } else {
            int opt = JOptionPane.showConfirmDialog(
                    this,
                    "tu es sur de suprimer?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION) {
                new ProductDAO()
                        .deleteProductDAO(tabelProduit.getValueAt(tabelProduit.getSelectedRow(), 0).toString());
                refrech();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_deleteProduitActionPerformed

    private void editProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProduitActionPerformed
        if (tabelProduit.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "il vaut selectionner un line dans le tableau.");
        } else {
            int row = tabelProduit.getSelectedRow();
            int col = tabelProduit.getColumnCount();
            Object[] data = new Object[col];

            for (int i = 0; i < col; i++) {

                data[i] = tabelProduit.getValueAt(row, i);
            }
            System.out.println(data[0]);
            new ProductForm(true, false, data);
            // ProductDTO productDTOEdit = new ProductDTO();
            // productForm.addButton.setEnabled(false);

            // System.out.println(productDTOEdit.toString());
            // // fournisseurForm.edit;
            // if (data[6] != null) {
            // productForm.loadDataSet(data[1].toString(), data[2].toString(),
            // data[3].toString(), data[4].toString(),
            // data[5].toString(), data[6].toString(), false);
            // } else {
            // productForm.loadDataSet(data[1].toString(), data[2].toString(),
            // data[3].toString(), data[4].toString(),
            // data[5].toString(), "0", true);
            // }
            // // this.setEnabled(false);
            // productForm.setVisible(true);
            refrech();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_editProduitActionPerformed

    private void editProduitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editProduitKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editProduitKeyPressed

    private void addProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProduitActionPerformed
        new ProductForm(false, true, null);
        refrech();        // TODO add your handling code here:
    }//GEN-LAST:event_addProduitActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        new Userform(false, true, null);
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserActionPerformed

    private void editUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserActionPerformed
        if (tabelUser.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "SLV slectionner un line dans le table pour le suprimer.");
        } else {
            int row = tabelUser.getSelectedRow();
            int col = tabelUser.getColumnCount();
            Object[] data = new Object[col];

            for (int i = 0; i < col; i++) {

                data[i] = tabelUser.getValueAt(row, i);
            }
            new Userform(true, false, data);

            refrech();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_editUserActionPerformed

    private void editUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUserKeyPressed

    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserActionPerformed
        if (tabelUser.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "SLV slectionner un line dans le table pour le suprimer.");
        } else {
            int opt = JOptionPane.showConfirmDialog(
                    this,
                    "tu es sure de suprimer le vendeur?",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (opt == JOptionPane.YES_OPTION) {

                String id = tabelUser.getValueAt(tabelUser.getSelectedRow(), 0).toString();
                new UserDAO().deleteUserDAO(Integer.parseInt(id));
                refrech();
                try {
                    loadData();
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserActionPerformed

    private void serchUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serchUserKeyReleased
        String text = serchUser.getText();
        loadSearchDataUser(text);      // TODO add your handling code here:
    }//GEN-LAST:event_serchUserKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void infoAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoAplikasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoAplikasiActionPerformed

    private void jMenuIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIExitActionPerformed
        System.exit(0);      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuIExitActionPerformed

    private void jMenuRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRefreshActionPerformed
        refrech();    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRefreshActionPerformed

    private void jMenuIExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIExit1ActionPerformed
dispose();
                new SallePage(username).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuIExit1ActionPerformed

    private void imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimerActionPerformed
float[] width = new float[]{20f, 40f, 30f, 40f  };
        ArrayList<String> name = new ArrayList<>();
        name.add("codeFourni"); 
        name.add("nom");
        name.add("lieu"); 
        name.add("telephone");
        
        String description = "Le table du fournisseur";
  
        try { 
            PDFTable.inBaoCao(description, new File("deidine.pdf"),
                    width, getCureentTime(), name, (DefaultTableModel) tablFourniseur.getModel());
            // TODO add your handling code here:
            
            // TODO add your handling code here:
        } catch (DocumentException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imprimerActionPerformed
private String getCureentTime() {

        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date dates = new Date();

        return dateFormat.format(dates);

    }

    private void imprimer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimer2ActionPerformed
float[] width = new float[]{20f, 20f, 50f, 20f, 40f, 40f  };
        ArrayList<String> name = new ArrayList<>();
       
        name.add("codeProd");
        name.add("nomProd"); 
          name.add("prxAchat");
        name.add("quentite");
          name.add("pxVende");
                name.add("marque");

        String description = "Le table du Commende";
  
        try { 
            PDFTable.inBaoCao(description, new File("deidine.pdf"),
                    width, getCureentTime(), name, (DefaultTableModel) tabelProduit.getModel());
            // TODO add your handling code here:
            
            // TODO add your handling code here:
        } catch (DocumentException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_imprimer2ActionPerformed

    private void imprimer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimer3ActionPerformed
float[] width = new float[]{20f, 20f, 50f, 20f, 40f  };
        ArrayList<String> name = new ArrayList<>();
        name.add("idAchat"); 
        name.add("codeProd");
        name.add("nomProd"); 
        name.add("quentite");
                name.add("totalpay");

        String description = "Le table du Commende";
  
        try { 
            PDFTable.inBaoCao(description, new File("deidine.pdf"),
                    width, getCureentTime(), name, (DefaultTableModel) tabelIPurchase.getModel());
            // TODO add your handling code here:
            
            // TODO add your handling code here:
        } catch (DocumentException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_imprimer3ActionPerformed

    private void imprimer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimer4ActionPerformed
float[] width = new float[]{20f, 40f, 30f, 40f  };
        ArrayList<String> name = new ArrayList<>();
        name.add("codeClient"); 
        name.add("nom");
        name.add("lieu"); 
        name.add("telephone");
        
        String description = "Le table du client";
  
        try { 
            PDFTable.inBaoCao(description, new File("deidine.pdf"),
                    width, getCureentTime(), name, (DefaultTableModel) tabelClient.getModel());
            // TODO add your handling code here:
            
            // TODO add your handling code here:
        } catch (DocumentException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_imprimer4ActionPerformed
    private void loadData() throws SQLException {
        // purchase table
        tabelIPurchase.setModel(prchtb.generateTable(limitPagination, counterPagination));

        // Client table
        tabelClient.setModel(cltb.generateTable(limitPagination, counterPagination));

//         salle table
        tabelUser.setModel(usertbl.generateTable());
        // loans table
        // tabelLouee.setModel(lntbl.generateTable());
        // product table
        tabelProduit.setModel(prtbl.generateTable(limitPagination, counterPagination));

        // Fournisseur table
        tablFourniseur.setModel(frtbl.generateTable(limitPagination, counterPagination));
    }

    public void loadSearchDataProduct(String text) {
        try {
            ProductDAO productDAO = new ProductDAO();
            tabelProduit.setModel(productDAO.buildTableModel(productDAO.getProductSearch(text)));
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }

    }

    public void loadSearchDataFournisseur(String text) {
        try {
            SupplierDAO supplierDAO = new SupplierDAO();
            tablFourniseur.setModel(supplierDAO.buildTableModel(supplierDAO.getSearchResult(text)));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void loadSearchDataUser(String text) {
        try {
            UserDAO usererDAO = new UserDAO();
            tabelUser.setModel(usererDAO.buildTableModel(usererDAO.getUserSearch(text)));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void loadSearchDataPurchase(String text) {

        try {
            ProductDAO productDAO = new ProductDAO();
            tabelIPurchase.setModel(productDAO.buildTableModel(productDAO.getPurchaseSearch(text)));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void loadSearchDataClient(String text) {

        try {
            CustomerDAO customerDAO = new CustomerDAO();
            tabelClient.setModel(customerDAO.buildTableModel(customerDAO.getCustomerSearch(text)));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    void refrech() {
        try {
            loadData();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard(username).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClient;
    private javax.swing.JButton addFournisseur;
    private javax.swing.JButton addProduit;
    private javax.swing.JButton addPurchase;
    private javax.swing.JButton addUser;
    private javax.swing.JButton deleteClient;
    private javax.swing.JButton deleteFournisseur;
    private javax.swing.JButton deleteProduit;
    private javax.swing.JButton deletePurchase;
    private javax.swing.JButton deleteUser;
    private javax.swing.JButton editClient;
    private javax.swing.JButton editFournisseur;
    private javax.swing.JButton editProduit;
    private javax.swing.JButton editUser;
    private javax.swing.JButton imprimer;
    private javax.swing.JButton imprimer2;
    private javax.swing.JButton imprimer3;
    private javax.swing.JButton imprimer4;
    private javax.swing.JMenuItem infoAplikasi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarInfoPengembang;
    private javax.swing.JMenuItem jMenuIExit;
    private javax.swing.JMenuItem jMenuIExit1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollTabelTransaksi10;
    private javax.swing.JScrollPane jScrollTabelTransaksi11;
    private javax.swing.JScrollPane jScrollTabelTransaksi6;
    private javax.swing.JScrollPane jScrollTabelTransaksi7;
    private javax.swing.JScrollPane jScrollTabelTransaksi9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton nextClient;
    private javax.swing.JButton nextFournisseur;
    private javax.swing.JButton nextProduct;
    private javax.swing.JButton nextPurchase;
    private javax.swing.JPanel panelClient;
    private javax.swing.JPanel panelFournisseur;
    private javax.swing.JButton prevClient;
    private javax.swing.JButton prevFournisseur;
    private javax.swing.JButton prevProduct;
    private javax.swing.JButton prevPurchase;
    private javax.swing.JTextField serchClient;
    private javax.swing.JTextField serchFournisseur;
    private javax.swing.JTextField serchProduct;
    private javax.swing.JTextField serchPurchase;
    private javax.swing.JTextField serchUser;
    private javax.swing.JTable tabelClient;
    private javax.swing.JTable tabelIPurchase;
    private javax.swing.JTable tabelProduit;
    private javax.swing.JTable tabelUser;
    private javax.swing.JTable tablFourniseur;
    // End of variables declaration//GEN-END:variables
}
